language: php
php:
- '7.0'
- '7.1'
- hhvm
- nightly
matrix:
  allow_failures:
  - php: nightly
install:
- composer install
- php artisan key:generate
- php artisan generate-api-token
script:
- bin/phpspec run
env:
  global:
- APP_ENV=local
- APP_KEY=base64:fX6cXEUEwPNw1UzWM8GurEyK8tOqvuY0Dl+gVZ9nL88=
- APP_DEBUG=true
- APP_LOG_LEVEL=debug
- APP_URL=http://localhost
- DB_CONNECTION=mysql
- DB_HOST=127.0.0.1
- DB_PORT=3306
- DB_DATABASE=oauth-server
- DB_USERNAME=travis
- DB_PASSWORD=secret
services:
- mysql
before_install:
  - mysql -e 'CREATE DATABASE oauth-server;'


