language: php
php:
- '7.0'
- '7.1'
- hhvm
- nightly
matrix:
  allow_failures:
  - php: nightly
install:
- composer install
- php artisan key:generate
- php artisan generate-api-token
script:
- bin/phpspec run
env:
  global:
  - APP_ENV=local
  - APP_DEBUG=true
  - APP_LOG_LEVEL=debug
  - APP_URL=http://localhost
  - DB_CONNECTION=mysql
  - DB_DATABASE=oauth_test
  - DB_USERNAME=travis
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE oauth_test;'

