language: php
php:
- '7.0'
- '7.1'
- hhvm
- nightly
matrix:
  allow_failures:
  - php: hhvm
  - php: nightly
install:
- composer install
- php artisan oauth2-server:install
- php artisan generate-api-token
env:
  global:
  - APP_ENV=local
  - APP_DEBUG=true
  - APP_LOG_LEVEL=debug
  - APP_URL=http://localhost
  - DB_CONNECTION=mysql
  - DB_DATABASE=oauth_test
  - DB_USERNAME=travis
  - secure: RSD4SSonItahrsg6Z/j0cO9jp8dvF90QXgrHBbzw8ZU8h9/ADF0FcLaOJ56kG7LKgr5gL6n7JqAIoCdbHdURlJywT3bfN5mgSTe+OX26xlyfPw8naPjoLusmZCysMEzkS0TQSsXg5EzLekEmRByQKcmyNcKoawjnrfpy92NYEKMb2rA+7Y2+PdN3C2DHWzlBh8JJBBUOZVq47lLT6rBj0YTREHk7C3TTQDYGwiw9QdFDdHr1XBHBcKZSqvwJZAhY1+5DV+nTd5HlTWxnVIjJUsVQMu75z8p3uAPdPbevgTbq/eNK7d196InhTkzf4lc+Npv62XKlaY8dk0xud2e9jBOyQ5qrxXqBIu1s9NtYJ+je4/N9gyFLBbrJOYonrE9fE2u/YCVcNCETSUV1gvXEjvY3dHsuG9x4gryt3G3RFCR1J7eIemBYpZRiWTgE2+U9bnlN6lYPfa/zjjK3T5RkoYJLPDRuy6LF44WUqabrgnKI3XjYv/oLkk508PjFjlmENvvexdrRSx1HZFun4P80XPia5yNlXb1eIPeWTh5vuRi7LsFiWAn1egdUPmA4DZn7N9EaNHz+6Qeu4lqjejUo82FAf+1wiaCltmwCZMsifI6fFSSfVX2V2e4QmcBOJiuZhhZZfUWXOiwEPuwyd3P+cMDUHH08xiNtj6XeMv+IAP0=
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE oauth_test;'
- echo $DEPLOY_URL
notifications:
  webhooks:
    urls:
      secure: Jh80T5bwS6gwpoyRXX894bjJvI06l1Rf6r3PMQvD5uKHdzPXuo0cNk3iZzGrUVLJT4V/OTB3Jfnu2Fxqw8qnKREXs6C+swKv9U46ja7mVGfg/E9GLeD5Qj0QlfO8sg4oyATu8EoOS8yZBL8TDkjnj2ZP+P48NY3SCNw+JDS7eLGWPWGb4ZGr/bjcXGI1DlChZHDJd/Me1Oy9yW18jpUv1Kxibh+p4biIR33bTHJGUvW/8frNXPZgWRw39SMuS6eqTc4km7z2lRxVPlvBHKVTOLWlo/WjAm4QaxxMdzRoe2ANorK2uylOrSBPwgQM7WGLbm0iDJ6DRG4xLK5pk+MbLuGV4Np+ftmjOsf/h1gbNDHF8Dy7afpEqCuUBMVEb6SeLdkV06DRQWz6BT24LgQwteQnJa+YnriczlVTS1mjxU2RF0vH3+NviX1dg3uLBKAXrXyZrTdZYm8OluTQTsKAMfi9rZOqqxeyjwnaGzsjH91tUSxJRMQp3vibomeW548SbFHShYAym9SdK/mOxLZHdjCb2kumgXQn0Sjpanl21woxKKo/vhi4HkyYiSf2/Cs13b6/0ObY7PoG/JGClE9kLG2lr5JbmOzgaIhh9f7YnQzuJTl1Cmf4XUOE7+G0EP5BSY3lviFFR4/wWzX6Nv2vASGbxPpiygp7/hUYAcoG85Q=
   on_success: always
   on_failure: never

